// TODO: Update the data
export const courses = [
  "BTech",
  "MSc(Int)",
  "MSc(2 yr)",
  "MTech",
  "PhD",
  "MT(Dual)",
  "MSc-PhD(Dual)",
  "MBA",
  "MDes",
  "BS",
  "MS-Research",
  "BT-MS",
  "BS-MS",
  "BS-MT",
  "BT-MBA",
  "BS-MBA",
  "BT-M.Des",
  "BS-M.Des",
  "MTech-PhD",
  "PhD-M.Des",
  "PhD-MS(Research)",
];

export const departmentNameMap = {
  "Aerospace Engineering": "AE",
  "Chemical Engineering": "CHE",
  "Civil Engineering": "CE",
  "Computer Science and Engineering": "CSE",
  "Electrical Engineering": "EE",
  "Industrial and Management Engineering": "IME",
  "Mechanical Engineering": "ME",
  "Materials Science and Engineering": "MSE",
  Chemistry: "CHM",
  "Mathematics and Statistics": "MATH",
  Physics: "PHY",
  Economics: "ECO",
  "Photonics Science and Engineering": "PSE",
  "Biological Sciences and Bioengineering": "BSBE",
  "Environmental Engineering and Management": "EEM",
  Design: "DES",
  "M Design": "MDES",
  "Earth Science": "ES",
  "Materials Science Programme": "MSP",
  "Cognitive Science": "CGS",
  "Humanities and Social Sciences": "HSS",
  Mathematics: "MTH",
  Statistics: "STAT",
  "Mathematics and Scientific Computing": "MTSC",
  "Sustainable Energy Engineering": "SEE",
  "Statistics and Data Science": "SDS",
  "Nuclear Engineering and Technology Programme": "NET",
  "Space Science and Astronomy": "SSA",
  "Sindhu Central University": "SCU",
  "Preparatory Course": "PREP",
  "Department Of Management Sciences": "DOMS",
  "Space, Planetary and Astronomical Sciences and Engineering": "SPAS",
  "C3I Hub": "C3IH",
  "Kotak School of Sustainability": "KSS",
  "DEPARTMENT OF INTELLIGENT SYSTEMS": "DIS",
  Other: "OTH",
};
export const halls = [
  "None",
  "HALL 1",
  "HALL 2",
  "HALL 3",
  "HALL 4",
  "HALL 5",
  "HALL 6",
  "HALL 7",
  "HALL 8",
  "HALL 9",
  "HALL X",
  "HALL XI",
  "HALL 12",
  "HALL 13",
  "HALL 14",
  "HALL 15",
  "GH",
  "DAY",
  "ACES",
  "CPWD",
  "RA",
  "NRA",
  "SBRA",
  "TYPE1",
  "TYPE1B",
  "TYPE5",
  "Other",
];
